Revert "ASoc: msm: Add dai link MultiMedia20 for custom card"
This reverts commit 2dc754853609f55d98954276e9a6b0acf1098cef.
Becuase needs to revert:
+++
d7baaa8 ASoc: msm: support SEC_MI2S_TX port routing to MultiMedia20
+++
Which causes build failure:
+++
../../../../../../kernel/sound/soc/msm/apq8096-auto.c:3116:12: error:
'MSM_FRONTEND_DAI_MULTIMEDIA20' undeclared here (not in a function)
   .be_id = MSM_FRONTEND_DAI_MULTIMEDIA20,
            ^
../../../../../../kernel/sound/soc/msm/apq8096-auto.c:3994:3: error:
initializer element is not constant
   .be_id = MSM_FRONTEND_DAI_MULTIMEDIA20
+++

Change-Id: I23dae7f2152f2922f45171d9b6b8b9fdf9734bf0
Signed-off-by: a7301c <a7301c@motorola.com>